server:
  port: 8888
spring:
  application:
    name: orderingsystem
  datasource:
    url: jdbc:mysql://localhost:3306/foodorder?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: Wap8778708
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.jie.entity